### ISSUE TITLE
How to pre-process KITTI data?

### ISSUE THREAD

**Issue by dataplayer12** [swords123/IDA-3D#11]
Hi @swords123 

Thank you for making the source code of your paper available. I am trying to reproduce your results, but I am facing a problem.

The server where you have uploaded the pre-processed dataset is really slow. So, I have been unable to download the dataset from the link provided by you. Instead, I went directly to the website of KITTI dataset and downloaded `data_object_image_2.zip` and `data_object_image_3.zip`. How do I pre-process this data to get it into the format expected by the training script?

**Comment by swords123** [comment]
It just generate xml files from the origin txt file since we can directly modify dataloader for Pacal VOC Dataset. The required values are calculated in advance according to the internal and external parameters. I am sorry that since my hard disk broke down during COVID-19, most of my python scripts have lost.  I will upload the data again to the other website in the future.

**Comment by dataplayer12** [comment]
Hi, thanks for replying to the issue. Can you tell me the specific steps you used to pre-process the data? Specifically, I am looking for the contents that need to be in `label_3d` directory. KITTI offers some code to convert annotations to Pascal voc format. DId you use them?
