### ISSUE TITLE
Single GPU use your code

### ISSUE THREAD

**Issue by Sukaiqi** [swords123/IDA-3D#12]
Hello, I use TITAN XP single card to run your code. I followed your instructions strictly. I just delete `-m torch.distributed.launch --nproc_per_node=2` in train.sh and test.sh file. But the results I got are lower from those mentioned in your paper. The result are produced from the model you provide. I don't know what went wrong, so I want to ask you.

The result is as follows：
car_detection AP: 90.297791 87.596001 78.844795
car_orientation AP: 90.119148 86.847435 77.664543
car_detection_ground AP: 69.266022 50.099205 43.286926
car_detection_3d AP: 53.662960 36.799820 32.361221

**Comment by swords123** [comment]
The result you have got is right! Since my disk is broken during the CONVID-19 last year,  the model file which is used in the paper is lost, so I upload another model file which is a little different from the results in the paper.
The result for this model what I have recorded is：
car_detection_ground AP: 69.27          50.10          43.29
car_detection_3d AP:          53.66          36.80          32.36
