### ISSUE TITLE
How to get label_3 from KITTI benchmark?

### ISSUE THREAD

**Issue by SlingHe** [swords123/IDA-3D#5]
Hi, I notice that your provide processed dataset and give a data folder format. I am confused about the 'label_3d'? How to get this file from the original KITTI 3D Benchmark? Please provide the data_generate codebase if it is generated by yourself.

**Comment by swords123** [comment]
It just generate xml files from the origin txt file since we can directly modify dataloader for Pacal VOC Dataset. The required values are calculated in advance according to the internal and external parameters. I am sorry that since my hard disk broke down during COVID-19, most of my python scripts have lost. I don't have time to write to rewrite them as present and I may provide the script in the future.

**Comment by SlingHe** [comment]
Thanks and then close this issue.
