### ISSUE TITLE
The link of processed dataset will get permission deny.

### ISSUE THREAD

**Issue by TCYuan** [swords123/IDA-3D#9]
Excuse me! 
When I downloaded processed dataset, I will get the permission deny.
Might you check the link of processed dataset or provide new link?
I'm very interested in your work.
Thank you very much.

**Comment by swords123** [comment]
Thanks for you interested in my work, I'm very sorry for my late reply! I test these links just now, and all hyperlinks are available. You can try again, and let me know if you get the same problem. If you have other questions if urgently, you can add my WeChat(qq1136558142) so that I can reply in time.
